config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/signed_in', to: 'users/sessions#show', as: 'session'
    put '/users/update', to: 'users#update'
  end

  resources :decks
  resources :deck_cards

  get 'games/lookup/:code' => "games#lookup"
  resources :games do
    get :logs, to: 'game_logs#index', as: 'logs'
  end
  resources :game_players
  resources :game_swaps

  get 'cards/guide' => "cards#guide"
  resources :cards do
    get 'flip'
  end
  post 'cards/sort' => "cards#sort"
  resources :card_relationships

  resources :rounds do
    resources :swaps
  end
  
  root 'ember#index'
  

end

app/models/round.rb
require 'printable/cards'
#require 'prawn/table'


class Round < ActiveRecord::Base
  Types = ["Basic", "Advanced"].freeze

  has_many :swaps

  default_scope { order "game_type DESC, number ASC"}

  validates :number, uniqueness: { scope: :game_type }

  def title
    "#{game_type} - Round #{number}"
  end

  def to_s
    title
  end

  include ActionView::Helpers::TextHelper
  def duration_with_unit
    pluralize(duration, "minute")
  end


  def swap_for(count)
    swaps.each do |swap|
      return swap if swap.include? count
    end
    nil
  end


  #for pdf creation

  Offsets = {
    duration: { at: [2.mm, 58.mm], width: 58.mm, height: 10.mm, align: :center },
    title:    { at: [2.mm, 55.mm], width: 58.mm, height: 10.mm, align: :center },
    swaps:    { at: [2.mm, 50.mm], width: 58.mm, height: 40.mm, align: :center }
  }.freeze 

  # include Printable::Cardable

  def self.render
    cards = Round.all
    cards << LeaderCard.new

    Printable::Cards.new.render(cards)
  end

  def quantity
    1
  end

  def render(document)
    # document.transparent(0.125) { document.stroke_bounds }

    document.font("Helvetica", style: :bold, size: 16) do
      document.text_box title, Round::Offsets[:title]
    end

    document.font("Helvetica", style: :italic, size: 10) do
      document.text_box duration_with_unit, Round::Offsets[:duration]
    end


    unless swaps.empty?
      document.bounding_box(Round::Offsets[:swaps][:at], Round::Offsets[:swaps]) do

        document.font("Courier", size: 8) do
          data = [ ["Players", "Hostages"] ]
          swaps.each do |swap|
            data << [swap.range , swap.count.to_s]
          end

          document.table(data, cell_style: {width: 29.mm }) do
          # document.table(data, position: :center) do
            cells.padding = 1
            cells.borders = []
            row(0).borders = [:bottom]
            row(0).style = :bold
            columns(0..1).align = :center
          end
        end


      end
    end

  end

end

class LeaderCard
  def quantity 
    1
  end
  def render(document)
    document.font("Helvetica", style: :bold, size: 40) do
      document.text_box "Leader", at: [2.mm, 55.mm], width: 58.mm, height: 20.mm, align: :center
    end
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: [:show, :edit, :update, :destroy]

  skip_before_filter :authenticate_user_from_token!, only: [:index, :show]
  skip_before_filter :authenticate_user!, only: [:index, :show]

  # GET /rounds
  # GET /rounds.json
  def index
    @rounds = Round.all

    respond_to do |format|
      format.html
      format.pdf { send_data Round.render, type: "application/pdf", disposition: "inline" }
      format.json { render json: @rounds }
    end
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
  end

  # GET /rounds/new
  def new
    @round = Round.new
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(round_params)

    respond_to do |format|
      if @round.save
        format.html { redirect_to @round, notice: 'Round was successfully created.' }
        format.json { render :show, status: :created, location: @round }
      else
        format.html { render :new }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to @round, notice: 'Round was successfully updated.' }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html { render :edit }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round.destroy
    respond_to do |format|
      format.html { redirect_to rounds_url, notice: 'Round was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_params
      params.require(:round).permit(:game_type, :number, :duration)
    end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_form.html.haml
= form_for @round do |f|
  - if @round.errors.any?
    #error_explanation
      %h2= "#{pluralize(@round.errors.count, "error")} prohibited this round from being saved:"
      %ul
        - @round.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :game_type
    = f.select :game_type, Round::Types
  .field
    = f.label :number
    = f.number_field :number
  .field
    = f.label :duration
    = f.number_field :duration
    minutes
  .actions
    = f.submit 'Save'

app/views/rounds/edit.html.haml
%h1 Editing round

= render 'form'

= link_to 'Show', @round
\|
= link_to 'Back', rounds_path

app/views/rounds/index.html.haml
%h1 Listing rounds

%table.grid
  %thead
    %tr
      %th Game type
      %th Number
      %th Duration
      %th 
      %th 
      
  %tbody
    - @rounds.each do |round|
      %tr
        %td= round.game_type
        %td= round.number
        %td= round.duration
        %td
          - unless round.swaps.empty?
            %table.grid
              %thead
                %tr
                  %th Players
                  %th Swaps
              %tbody
                - round.swaps.each do |swap|
                  %tr
                    %td= swap.range
                    %td= swap.count

        %td
          = link_to 'Show', round
          = link_to 'Swaps', round_swaps_path(round)
          = link_to 'Edit', edit_round_path(round)
          = link_to 'Destroy', round, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Round', new_round_path
\|
= link_to "Generate PDF", rounds_path(format: :pdf)

app/views/rounds/new.html.haml
%h1 New round

= render 'form'

= link_to 'Back', rounds_path

app/views/rounds/show.html.haml
%p
  %b Game type:
  = @round.game_type
%p
  %b Number:
  = @round.number
%p
  %b Duration:
  = @round.duration

= link_to 'Edit', edit_round_path(@round)
\|
= link_to 'Back', rounds_path