config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/signed_in', to: 'users/sessions#show', as: 'session'
    put '/users/update', to: 'users#update'
  end

  resources :decks
  resources :deck_cards

  get 'games/lookup/:code' => "games#lookup"
  resources :games do
    get :logs, to: 'game_logs#index', as: 'logs'
  end
  resources :game_players
  resources :game_swaps

  get 'cards/guide' => "cards#guide"
  resources :cards do
    get 'flip'
  end
  post 'cards/sort' => "cards#sort"
  resources :card_relationships

  resources :rounds do
    resources :swaps
  end
  
  root 'ember#index'
  

end

app/models/card.rb
require 'printable/cards'

class Card < ActiveRecord::Base
  COLORS = ["Blue", "Red", "Grey"].freeze
  FACTIONS = COLORS

  default_scope { order("sort_order asc") }
  scope :alpha, -> { order("title asc, color asc") }
  scope :color, -> { order("color asc, title asc") }
  
  has_many :relationships, :class_name => "CardRelationship", :foreign_key => "card_id"
  has_many :relations, :through => :relationships, :source => :to
  has_many :inverse_relationships, :class_name => "CardRelationship", :foreign_key => "to_id"
  has_many :inverse_relations, :through => :inverse_relationships, :source => :card

  validates :title, presence: true
  validates :title, uniqueness: { scope: :faction }
  validates :faction, presence: true

  def relationships_grouped
    relationships.group_by(&:description)
  end

  def inverse_relationships_grouped
    inverse_relationships.group_by(&:description)
  end

  # def enemies
  #   relationships_grouped["Enemy"].collect(&:to) unless relationships_grouped["Enemy"].nil?
  # end

  # def enemies_of
  #   unless inverse_relationships_grouped["Enemy"].nil?
  #     enemies_of = inverse_relationships_grouped["Enemy"].collect(&:card)

  #     mutual = enemies
  #     unless mutual.nil?
  #       enemies_of.reject! { |enemy_of| mutual.include?(enemy_of) }
  #     end
  #     enemies_of
  #   end
  # end
  RelationshipTypes = { enemies: "Enemy", allies: "Ally", requires: "Required", recommends: "Recommended" }.freeze
  RelationshipTypes.each do |method, description|

    define_method(method.to_s) do 
      unless relationships_grouped[description].nil?
        relationships_grouped[description].collect(&:to)
      else
        []
      end
    end

    define_method(method.to_s + "_of") do
      unless inverse_relationships_grouped[description].nil?
        inverse = inverse_relationships_grouped[description].collect(&:card)

        mutual = send(method)
        unless mutual.nil?
          inverse.reject! { |inv| mutual.include? inv }
        end

        inverse
      else
        []
      end
    end
  end
  def required_by; requires_of; end
  def recommended_by; recommends_of; end

  def team
    case faction
    when "Blue"
        "You are on the Blue Team"
    when "Red"
       "You are on the Red Team"
    else 
      "You are not on a team"
    end
  end

  def title_with_color
    "#{title} (#{color})"
  end
  def icon
    case faction
    when "Blue"
      "images/star.png"
    when "Red"
      "images/bomb.png"
    else
      "images/grey.png"
    end
  end

  def print_icon
    case faction
    when "Blue"
      "images/print-star.png"
    when "Red"
      "images/print-bomb.png"
    else
      "images/print-grey.png"
    end
  end
  def large_icon; print_icon; end

  def flip
    map = { 
      "Blue" => "Red",
      "Red" => "Blue",
      "Grey" => "Grey",
    }

    flipped = dup
    flipped.color = map[color]
    flipped.faction = map[faction]

    [:subtitle, :short_desc, :long_desc, :strategy].each do |field|

      val = flipped.send(field)

      # swap
      val.gsub!(/Blue/, "Cyan")
      val.gsub!(/Red/, "Blue")
      val.gsub!(/Cyan/, "Red")

      flipped.send("#{field}=", val)
    end

    flipped
  end



  Offsets = {
    icon:        {at: [ 20.mm, 64.mm], width:    64, height: 64, align: :center},
    title:       {at: [  2.mm, 55.mm], width: 58.mm, height: 10.mm, align: :center},
    subtitle:    {at: [  2.mm, 48.mm], width: 58.mm, height: 10.mm, align: :center},
    description: {at: [  2.mm, 40.mm], width: 58.mm, height: 20.mm, align: :center},
    color:       {at: [ 46.mm,  5.mm], width: 15.mm, height: 10.mm, align: :right},
  }.freeze

  # include Printable::Cardable

  #render the whole file
  def self.render
    Printable::Cards.new.render(Card.all)
  end

  # def quantity
  #   @quantity
  # end

  #render one card
  def render(document)
    # document.transparent(0.5) { document.stroke_bounds }

    if icon
      document.transparent(0.25) do
        document.image "#{Rails.root.join('public')}/#{print_icon}", Card::Offsets[:icon]
      end
    end

    document.font("Helvetica", style: :bold, size: 16) do
      document.text_box title.gsub(/`/, ""), Card::Offsets[:title]
    end
    document.font("Helvetica", style: :italic, size: 10) do
      document.text_box subtitle.gsub(/`/, ""), Card::Offsets[:subtitle]
    end
    document.font("Courier", size: 8) do
      document.text_box short_desc.gsub(/`/, ""), Card::Offsets[:description]
    end

    # document.font("Courier", size: 6) do
    #   document.text_box long_desc.gsub(/`/, ""), at: [2.mm, 25.mm], width: 58.mm, height: 25.mm, align: :justify
    # end

    # document.font("Helvetica", style: :bold, size: 12) do
    #   document.text_box color.gsub(/`/, ""), Card::Offsets[:color]
    # end

  end

end

app/models/printable/cards.rb
require 'printable'

module Printable
	class Cards < Base

    CardOffsets = { 
      0 => [   0.mm, 264.mm],
      1 => [  62.mm, 264.mm],
      2 => [ 124.mm, 264.mm],
      3 => [   0.mm, 176.mm],
      4 => [  62.mm, 176.mm],
      5 => [ 124.mm, 176.mm],
      6 => [   0.mm,  88.mm],
      7 => [  62.mm,  88.mm],
      8 => [ 124.mm,  88.mm]
    }.freeze

    CardSize = {
      width: 62.mm,
      height: 88.mm
    }.freeze 

    def initialize()
      super
      @card_number = 0
      @current_color = "Blue"
    end

    def render(set)
      #set = []
      super() do
        # @card_number = 0
        set.each do |card|
          card.quantity.times do
            render_card card
          end
        end
      end
    end

    def render_card(card)
      if card.color != @current_color
        @card_number = (@card_number / 9.0).ceil * 9
      end

      pos = (@card_number % 9)
      row = pos / 3
      col = @card_number % 3

      offset = Printable::Cards::CardOffsets[pos]

      if @card_number != 0 and pos % 9 == 0  
        @pdf.start_new_page
      end


      @pdf.bounding_box(offset, Printable::Cards::CardSize) do
        card.render @pdf
      end

      @current_color = card.color
      @card_number += 1
    end
	end

  # module Cardable

  #   # def quantity
  #   #   instance_variable_get(:@quantity) || 1
  #   # end

  #   # def render(pdf)
  #   # end
  # end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  skip_before_filter :authenticate_user_from_token!, only: [:index, :show]
  skip_before_filter :authenticate_user!, only: [:index, :show]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all

    respond_to do |format|
      format.html
      format.pdf { send_data Card.render, type: "application/pdf", disposition: "inline" }
      format.json { render json: @cards }
    end
  end

  def guide
    @cards = Card.unscoped.order("title ASC, color ASC").all
    respond_to do |format|
      format.html
      format.pdf { send_data Card.guide, type: "application/pdf", disposition: "inline" }
    end
  end


  # GET /cards/1
  # GET /cards/1.json
  def show
    cards = [@card]
    @card.relationships.each do |r|
      cards << r.to
    end
    @card.inverse_relationships.each do |ir|
      cards << ir.to
    end

    respond_to do |format|
      format.html
      format.json { render json: cards }
    end
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to cards_path, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def flip
    @card = Card.find(params[:card_id])
    flipped = @card.flip
    respond_to do |format|
      if flipped.save
        format.html { redirect_to cards_path, notice: 'Card was successfully flipped.' }
        format.json { render :show, status: :created, location: flipped }
      else
        format.html { render :new }
        format.json { render json: flipped.errors, status: :unprocessable_entity }
      end
    end
  end

  def sort
    order = params[:order].split(",")
    cur = 1
    order.each do |card_id|
      card = Card.find(card_id)
      unless card.nil?
        card.sort_order = cur 
        card.save
        cur += 1
      end
    end

    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card order updated.' }
      format.json { render json: { code: :sort_updated, message: "Card order updated."} }
    end

  end



  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to cards_path, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:title, :subtitle, :short_desc, :long_desc, :color, :faction, :strategy, :required_text, :recommended_text, :quantity)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.haml
= form_for @card do |f|
  - if @card.errors.any?
    #error_explanation
      %h2= "#{pluralize(@card.errors.count, "error")} prohibited this card from being saved:"
      %ul
        - @card.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :subtitle
    = f.text_field :subtitle
  .field
    = f.label :short_desc
    = f.text_area :short_desc, class: :short_desc
  .field
    = f.label :long_desc
    = f.text_area :long_desc
  .field
    = f.label :color
    = f.select :color, Card::COLORS
  .field
    = f.label :faction
    = f.select :faction, Card::FACTIONS
  .field
    = f.label :strategy
    = f.text_area :strategy
  .field
    = f.label :required_text, "Requires"
    = f.text_area :required_text
  .field
    = f.label :recommended_text, "Recommended"
    = f.text_area :recommended_text
  .field
    = f.label :quantity
    = f.text_field :quantity, type: :number
  .actions
    = f.submit 'Save'

app/views/cards/_full.html.haml
%div.card
  %div{class: ["color", full.color], data: {color: full.color}}
    .title= full.title
    .subtitle= full.subtitle
    .description= full.short_desc
    %div{class: ["faction", full.faction], data: {faction: full.faction}, title: full.team}
      

app/views/cards/_short.html.haml
%span.card
  %span{class: ["color", short.color], data: {color: short.color}}
    %span{class: ["faction", short.faction], data: {faction: short.faction}, title: short.team}
      = short.title

app/views/cards/edit.html.haml
%h1 Editing card

= render 'form'

= link_to 'Back', cards_path

app/views/cards/guide.html.haml
%header
  %h2 Two Rooms and a Boom 
  %h1 Character Guide
- @cards.group_by(&:title).each do |title, cards|
  .guide
    %header
      %h2
        - cards.each do |card|
          = render partial: 'short', object: card
          &nbsp;
    - card = cards.first
    %p= markdown card.long_desc
    .row
      - unless card.strategy.blank?
        %div
          %b Strategy:
          %p
            = markdown(card.strategy)


      - unless card.allies.empty?
        %div
          %b Allies:
          %p 
            - card.allies.each do |c|
              = render partial: "short", object: c
              &nbsp;

      - unless card.allies_of.empty?
        %div
          %b Ally of:
          %p
            - card.allies_of.each do |c|
              = render partial: "short", object: c
              &nbsp;


      - unless card.enemies.empty?
        %div
          %b Enemies:
          %p 
            - card.enemies.each do |c|
              = render partial: "short", object: c
              &nbsp;

      - unless card.enemies_of.empty?
        %div
          %b Enemy of:
          %p
            - card.enemies_of.each do |c|
              = render partial: "short", object: c
              &nbsp;


      - unless card.requires.empty? and card.required_text.blank?
        %div
          %b Requires:
          - unless card.required_text.blank?
            %p 
              = markdown card.required_text
          - unless card.requires.empty?
            %p
              - card.requires.each do |c|
                = render partial: "short", object: c
                &nbsp;

      - unless card.required_by.empty?
        %div
          %b Required by:
          %p
            - card.required_by.each do |c|
              = render partial: "short", object: c
              &nbsp;

      - unless card.recommends.empty? and card.recommended_text.blank?
        %div
          %b Recommended:
          - unless card.recommended_text.blank?
            %p
              = markdown card.recommended_text
          - unless card.recommends.empty?
            %p 
              - card.recommends.each do |c|
                = render partial: "short", object: c
                &nbsp;

      - unless card.recommended_by.empty?
        %div
          %b Recommended By:
          %p
            - card.recommended_by.each do |c|
              = render partial: "short", object: c
              &nbsp;
    %br


.no-print
  = link_to "Back", cards_path

app/views/cards/index.html.haml
%h1 Listing cards

%table.table.cards.full.grid.sortable{data: {action: "/cards/sort.json"}}
  %thead
    %tr
      %th Title
      %th Short desc
      %th
      
  %tbody
    - @cards.each do |card|
      %tr{data: {key: card.id}}
        %td
          = render partial: 'short', object: card
          %div
            = card.subtitle
            - unless card.quantity == 1
              = "(#{card.quantity}x)"
        %td= card.short_desc
        %td
          = link_to 'Show', card
          = link_to 'Move', '#', class: :move
          = link_to 'Edit', edit_card_path(card)
          = link_to 'Flip', card_flip_path(card)
          = link_to 'Destroy', card, :method => :delete, :data => { :confirm => 'Are you sure?' }
  %tfoot
    %tr
      %th
        = "#{pluralize(@cards.length, "total cards")}"
        %br
        = "#{pluralize(@cards.group_by(&:title).length, "unique titles")}"
      %th
        .blue= "#{pluralize(@cards.select{|c| c.color == "Blue" }.length, "Blue Cards")}"
        .red= "#{pluralize(@cards.select{|c| c.color == "Red" }.length, "Red Cards")}"
        .grey= "#{pluralize(@cards.select{|c| c.color == "Grey" }.length, "Grey Cards")}"
      %th
%br

= link_to 'New Card', new_card_path
\|
= link_to "Relationships", card_relationships_path
%br
= link_to "Card PDF", cards_path(format: :pdf)
\|
= link_to "Character Guide", cards_guide_path # (format: :pdf)

app/views/cards/new.html.haml
%h1 New card

= render 'form'

= link_to 'Back', cards_path

app/views/cards/show.html.haml
%p Full Card:
= render partial: "full", object: @card

%p Short Card:
= render partial: "short", object: @card


%hr
%header
  %h1 Guide text:
  %h2= render partial: "short", object: @card

= markdown(@card.long_desc)


- unless @card.strategy.blank?
  %b Strategy:
  %p
    = markdown(@card.strategy)


- unless @card.allies.empty?
  %b Allies:
  %p 
    - @card.allies.each do |card|
      = render partial: "short", object: card
      &nbsp;

- unless @card.allies_of.empty?
  %b Ally of:
  %p
    - @card.allies_of.each do |card|
      = render partial: "short", object: card
      &nbsp;


- unless @card.enemies.empty?
  %b Enemies:
  %p 
    - @card.enemies.each do |card|
      = render partial: "short", object: card
      &nbsp;

- unless @card.enemies_of.empty?
  %b Enemy of:
  %p
    - @card.enemies_of.each do |card|
      = render partial: "short", object: card
      &nbsp;


- unless @card.requires.empty? and @card.required_text.blank?
  %b Requires:
  - unless @card.required_text.blank?
    %p 
      = markdown @card.required_text
  - unless @card.requires.empty?
    %p
      - @card.requires.each do |card|
        = render partial: "short", object: card
        &nbsp;

- unless @card.required_by.empty?
  %b Required by:
  %p
    - @card.required_by.each do |card|
      = render partial: "short", object: card
      &nbsp;

- unless @card.recommends.empty? and @card.recommended_text.blank?
  %b Recommended:
  - unless @card.recommended_text.blank?
    %p
      = markdown @card.recommended_text
  - unless @card.recommends.empty?
    %p 
      - @card.recommends.each do |card|
        = render partial: "short", object: card
        &nbsp;

- unless @card.recommended_by.empty?
  %b Recommended By:
  %p
    - @card.recommended_by.each do |card|
      = render partial: "short", object: card
      &nbsp;


%hr
%p
  %b Title:
  = @card.title
%p
  %b Subtitle:
  = @card.subtitle
%p
  %b Short desc:
  = markdown(@card.short_desc)
%p
  %b Long desc:
  = markdown(@card.long_desc)
%p
  %b Color:
  = @card.color
%p
  %b Faction:
  = @card.faction
%p
  %b Strategy:
  = markdown(@card.strategy)
%p
  %b Url:
  = @card.url

= link_to 'Edit', edit_card_path(@card)
\|
= link_to 'Back', cards_path