config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/signed_in', to: 'users/sessions#show', as: 'session'
    put '/users/update', to: 'users#update'
  end

  resources :decks
  resources :deck_cards

  get 'games/lookup/:code' => "games#lookup"
  resources :games do
    get :logs, to: 'game_logs#index', as: 'logs'
  end
  resources :game_players
  resources :game_swaps

  get 'cards/guide' => "cards#guide"
  resources :cards do
    get 'flip'
  end
  post 'cards/sort' => "cards#sort"
  resources :card_relationships

  resources :rounds do
    resources :swaps
  end
  
  root 'ember#index'
  

end

app/models/swap.rb
class Swap < ActiveRecord::Base
  belongs_to :round
  
  default_scope { order "round_id ASC, player_min ASC"}


  def range
    unless player_max.blank?
      "#{player_min} - #{player_max}"
    else
      "#{player_min} +"
    end
  end

  def include?(count)
    player_min <= count and (! player_max or count <= player_max)
  end
end

app/controllers/swaps_controller.rb
class SwapsController < ApplicationController
  before_action :set_round
  before_action :set_swap, only: [:show, :edit, :update, :destroy]

  # GET /swaps
  # GET /swaps.json
  def index
    @swaps = @round.swaps
  end

  # GET /swaps/1
  # GET /swaps/1.json
  def show
  end

  # GET /swaps/new
  def new
    prev_max = 5
    prev_max = @round.swaps.last.player_max unless @round.swaps.empty?
    @swap = @round.swaps.new
    @swap.player_min = prev_max + 1
    @swap.player_max = prev_max + 2
    @swap.count = 1
  end

  # GET /swaps/1/edit
  def edit
  end

  # POST /swaps
  # POST /swaps.json
  def create
    @swap = @round.swaps.new(swap_params)

    respond_to do |format|
      if @swap.save
        format.html { redirect_to round_swaps_path(@round), notice: 'Swap was successfully created.' }
        format.json { render :show, status: :created, location: @swap }
      else
        format.html { render :new }
        format.json { render json: @swap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /swaps/1
  # PATCH/PUT /swaps/1.json
  def update
    respond_to do |format|
      if @swap.update(swap_params)
        format.html { redirect_to round_swaps_path(@round), notice: 'Swap was successfully updated.' }
        format.json { render :show, status: :ok, location: @swap }
      else
        format.html { render :edit }
        format.json { render json: @swap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /swaps/1
  # DELETE /swaps/1.json
  def destroy
    @swap.destroy
    respond_to do |format|
      format.html { redirect_to round_swaps_url(@round), notice: 'Swap was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:round_id])
    end

    def set_swap
      @swap = Swap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def swap_params
      params.require(:swap).permit(:round_id, :player_min, :player_max, :count)
    end
end

app/helpers/swaps_helper.rb
module SwapsHelper
end

app/views/swaps/_form.html.haml
= form_for [@round, @swap] do |f|
  - if @swap.errors.any?
    #error_explanation
      %h2= "#{pluralize(@swap.errors.count, "error")} prohibited this swap from being saved:"
      %ul
        - @swap.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :round_id
  .field
    = f.label :player_min
    = f.number_field :player_min
  .field
    = f.label :player_max
    = f.number_field :player_max
  .field
    = f.label :count
    = f.number_field :count
  .actions
    = f.submit 'Save'

app/views/swaps/edit.html.haml
%h1= "Editing swap for #{@round}"

= render 'form'

= link_to 'Show', round_swap_path(@round, @swap)
\|
= link_to 'Back', round_swaps_path(@round)

app/views/swaps/index.html.haml
%h1= "Listing swaps for #{@round}"

%table.grid
  %thead
    %tr
      %th Players
      %th Count
      %th
      
  %tbody
    - @swaps.each do |swap|
      %tr
        %td= swap.range
        %td= swap.count
        %td
          = link_to 'Show', round_swap_path(@round, swap)
          = link_to 'Edit', edit_round_swap_path(@round, swap)
          = link_to 'Destroy', round_swap_path(@round, swap), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Swap', new_round_swap_path(@round)
\|
= link_to 'Back', rounds_path

app/views/swaps/new.html.haml
%h1= "New swap for #{@round}"

= render 'form'

= link_to 'Back', round_swaps_path(@round)

app/views/swaps/show.html.haml
%p
  %b Round:
  = @swap.round_id
%p
  %b Player min:
  = @swap.player_min
%p
  %b Player max:
  = @swap.player_max
%p
  %b Count:
  = @swap.count

= link_to 'Edit', edit_round_swap_path(@round, @swap)
\|
= link_to 'Back', round_swaps_path(@round)