config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/signed_in', to: 'users/sessions#show', as: 'session'
    put '/users/update', to: 'users#update'
  end

  resources :decks
  resources :deck_cards

  get 'games/lookup/:code' => "games#lookup"
  resources :games do
    get :logs, to: 'game_logs#index', as: 'logs'
  end
  resources :game_players
  resources :game_swaps

  get 'cards/guide' => "cards#guide"
  resources :cards do
    get 'flip'
  end
  post 'cards/sort' => "cards#sort"
  resources :card_relationships

  resources :rounds do
    resources :swaps
  end
  
  root 'ember#index'
  

end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %title TwoRooms
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag    'application'
    = csrf_meta_tags
    %link{ rel: "icon", type: "image/png", href: "/images/bomb.png"}
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1"}
    /%meta{ name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"}
  %body
    = bootstrap_flash
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed(data-toggle="collapse" data-target="#navbar-collapse")
          = link_to "TwoRooms", root_url, class: "navbar-brand"
        #navbar-collapse.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to "Cards", cards_path
            %li= link_to "Rounds", rounds_path
            %li= link_to "Decks", decks_path
            - unless current_user.nil?
              %li.dropdown
                = link_to current_user, {:class => "dropdown-toggle", data: {toggle: "dropdown"}} do 
                  = current_user.name || "Profile"
                  %span.caret
                %ul.dropdown-menu
                  %li= link_to "Edit", edit_user_path(current_user)
                  %li= link_to "Log out", destroy_user_session_path, method: "delete"
    .container-fluid
      .row
        .col-md-12
          = yield

app/views/layouts/ember.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no")
    %title= content_for?(:title) ? yield(:title) : "TwoRooms"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "ember-app"


  %body
    = yield